In [41]:
from sklearn import preprocessing
from datetime import date, timedelta
import matplotlib.pyplot as plt

In [42]:
# scikit-learn
# 正規化

#1-D list
l = [0, 1, 2, 3, 4]

#2-D list
l_2d = [
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8]
    ]

l_2d

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [43]:
#インスタンスを生成してからfit_transform()メソッドを使う。正規化されたnumpy.ndarrayが返る。
#MinMaxScalerクラスでは一次元配列は処理されず、二次元配列のみが対象。列ごとに正規化され、行ごとや全体に対する処理はできない。

mm = MinMaxScaler()

l_2d_min_max = mm.fit_transform(l_2d)

l_2d_min_max

array([[0. , 0. , 0. ],
       [0.5, 0.5, 0.5],
       [1. , 1. , 1. ]])

In [44]:
#直接処理するminmax_scale()関数もある。
#こちらは一次元配列も処理可能。また、二次元配列に対して引数axis=1とすると行ごとの処理となる。全体に対する処理はできない。

print(preprocessing.minmax_scale(l))
print(preprocessing.minmax_scale(l_2d))
print(preprocessing.minmax_scale(l_2d, axis=1))

[0.   0.25 0.5  0.75 1.  ]
[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]
[[0.  0.5 1. ]
 [0.  0.5 1. ]
 [0.  0.5 1. ]]


In [48]:
#標準化
#平均0、分散1に正規化（標準化）するにはStandardScalerクラスまたはscale()関数を使う。
#使い方および制限は上述のMinMaxScalerクラス、minmax_scale()関数と同じ。

ss = preprocessing.StandardScaler()

l_2d_standardization = ss.fit_transform(l_2d)

l_2d_standardization

array([[-1.22474487, -1.22474487, -1.22474487],
       [ 0.        ,  0.        ,  0.        ],
       [ 1.22474487,  1.22474487,  1.22474487]])

In [49]:
print(preprocessing.scale(l))
print(preprocessing.scale(l_2d))
print(preprocessing.scale(l_2d, axis=1))

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]
[[-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]]
